---
name: SimpleAlias
version: 1.0.1
main: SimpleAlias\Loader
api: 3.0.0
author: DC
description: New & updated alias plugin.

commands:
    alias:
        description: Check all usernames of a certain player!
        permission: simplealias.command
permissions:
  simplealias.command:
    default: op
    description: "Perm to run the command: /alias <player>"
...
