---
name: AliasReborn
version: 1.0.0
main: AliasReborn\Main
api: [3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4]
load: STARTUP
author: ArceusMatt
description: New & updated alias plugin.
website: https://github.com/arceusmatt

commands:
    alias:
        description: Check usernames of a player.
        permission: alias.cmd
permissions:
  alias.cmd:
    default: op
    description: "Permission for /alias."
...
